/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DangNhapRouteImport } from './routes/dang-nhap'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TruyenIndexRouteImport } from './routes/truyen.index'
import { Route as TruyenSlugIndexRouteImport } from './routes/truyen.$slug.index'
import { Route as TruyenSlugChuongNumberRouteImport } from './routes/truyen.$slug.chuong-$number'

const DangNhapRoute = DangNhapRouteImport.update({
  id: '/dang-nhap',
  path: '/dang-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TruyenIndexRoute = TruyenIndexRouteImport.update({
  id: '/truyen/',
  path: '/truyen/',
  getParentRoute: () => rootRouteImport,
} as any)
const TruyenSlugIndexRoute = TruyenSlugIndexRouteImport.update({
  id: '/truyen/$slug/',
  path: '/truyen/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const TruyenSlugChuongNumberRoute = TruyenSlugChuongNumberRouteImport.update({
  id: '/truyen/$slug/chuong-$number',
  path: '/truyen/$slug/chuong-$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dang-nhap': typeof DangNhapRoute
  '/truyen/': typeof TruyenIndexRoute
  '/truyen/$slug/chuong-$number': typeof TruyenSlugChuongNumberRoute
  '/truyen/$slug/': typeof TruyenSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dang-nhap': typeof DangNhapRoute
  '/truyen': typeof TruyenIndexRoute
  '/truyen/$slug/chuong-$number': typeof TruyenSlugChuongNumberRoute
  '/truyen/$slug': typeof TruyenSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dang-nhap': typeof DangNhapRoute
  '/truyen/': typeof TruyenIndexRoute
  '/truyen/$slug/chuong-$number': typeof TruyenSlugChuongNumberRoute
  '/truyen/$slug/': typeof TruyenSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dang-nhap'
    | '/truyen/'
    | '/truyen/$slug/chuong-$number'
    | '/truyen/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dang-nhap'
    | '/truyen'
    | '/truyen/$slug/chuong-$number'
    | '/truyen/$slug'
  id:
    | '__root__'
    | '/'
    | '/dang-nhap'
    | '/truyen/'
    | '/truyen/$slug/chuong-$number'
    | '/truyen/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DangNhapRoute: typeof DangNhapRoute
  TruyenIndexRoute: typeof TruyenIndexRoute
  TruyenSlugChuongNumberRoute: typeof TruyenSlugChuongNumberRoute
  TruyenSlugIndexRoute: typeof TruyenSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dang-nhap': {
      id: '/dang-nhap'
      path: '/dang-nhap'
      fullPath: '/dang-nhap'
      preLoaderRoute: typeof DangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truyen/': {
      id: '/truyen/'
      path: '/truyen'
      fullPath: '/truyen/'
      preLoaderRoute: typeof TruyenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truyen/$slug/': {
      id: '/truyen/$slug/'
      path: '/truyen/$slug'
      fullPath: '/truyen/$slug/'
      preLoaderRoute: typeof TruyenSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truyen/$slug/chuong-$number': {
      id: '/truyen/$slug/chuong-$number'
      path: '/truyen/$slug/chuong-$number'
      fullPath: '/truyen/$slug/chuong-$number'
      preLoaderRoute: typeof TruyenSlugChuongNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DangNhapRoute: DangNhapRoute,
  TruyenIndexRoute: TruyenIndexRoute,
  TruyenSlugChuongNumberRoute: TruyenSlugChuongNumberRoute,
  TruyenSlugIndexRoute: TruyenSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
