/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TuSachRouteImport } from './routes/tu-sach'
import { Route as DangNhapRouteImport } from './routes/dang-nhap'
import { Route as DangKyRouteImport } from './routes/dang-ky'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TruyenIndexRouteImport } from './routes/truyen.index'
import { Route as TruyenSlugIndexRouteImport } from './routes/truyen.$slug.index'
import { Route as TruyenSlugChuongChar123numberChar125RouteImport } from './routes/truyen.$slug.chuong-{$number}'

const TuSachRoute = TuSachRouteImport.update({
  id: '/tu-sach',
  path: '/tu-sach',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapRoute = DangNhapRouteImport.update({
  id: '/dang-nhap',
  path: '/dang-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyRoute = DangKyRouteImport.update({
  id: '/dang-ky',
  path: '/dang-ky',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TruyenIndexRoute = TruyenIndexRouteImport.update({
  id: '/truyen/',
  path: '/truyen/',
  getParentRoute: () => rootRouteImport,
} as any)
const TruyenSlugIndexRoute = TruyenSlugIndexRouteImport.update({
  id: '/truyen/$slug/',
  path: '/truyen/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const TruyenSlugChuongChar123numberChar125Route =
  TruyenSlugChuongChar123numberChar125RouteImport.update({
    id: '/truyen/$slug/chuong-{$number}',
    path: '/truyen/$slug/chuong-{$number}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/tu-sach': typeof TuSachRoute
  '/truyen/': typeof TruyenIndexRoute
  '/truyen/$slug/chuong-{$number}': typeof TruyenSlugChuongChar123numberChar125Route
  '/truyen/$slug/': typeof TruyenSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/tu-sach': typeof TuSachRoute
  '/truyen': typeof TruyenIndexRoute
  '/truyen/$slug/chuong-{$number}': typeof TruyenSlugChuongChar123numberChar125Route
  '/truyen/$slug': typeof TruyenSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/tu-sach': typeof TuSachRoute
  '/truyen/': typeof TruyenIndexRoute
  '/truyen/$slug/chuong-{$number}': typeof TruyenSlugChuongChar123numberChar125Route
  '/truyen/$slug/': typeof TruyenSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dang-ky'
    | '/dang-nhap'
    | '/tu-sach'
    | '/truyen/'
    | '/truyen/$slug/chuong-{$number}'
    | '/truyen/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dang-ky'
    | '/dang-nhap'
    | '/tu-sach'
    | '/truyen'
    | '/truyen/$slug/chuong-{$number}'
    | '/truyen/$slug'
  id:
    | '__root__'
    | '/'
    | '/dang-ky'
    | '/dang-nhap'
    | '/tu-sach'
    | '/truyen/'
    | '/truyen/$slug/chuong-{$number}'
    | '/truyen/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DangKyRoute: typeof DangKyRoute
  DangNhapRoute: typeof DangNhapRoute
  TuSachRoute: typeof TuSachRoute
  TruyenIndexRoute: typeof TruyenIndexRoute
  TruyenSlugChuongChar123numberChar125Route: typeof TruyenSlugChuongChar123numberChar125Route
  TruyenSlugIndexRoute: typeof TruyenSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tu-sach': {
      id: '/tu-sach'
      path: '/tu-sach'
      fullPath: '/tu-sach'
      preLoaderRoute: typeof TuSachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-nhap': {
      id: '/dang-nhap'
      path: '/dang-nhap'
      fullPath: '/dang-nhap'
      preLoaderRoute: typeof DangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-ky': {
      id: '/dang-ky'
      path: '/dang-ky'
      fullPath: '/dang-ky'
      preLoaderRoute: typeof DangKyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truyen/': {
      id: '/truyen/'
      path: '/truyen'
      fullPath: '/truyen/'
      preLoaderRoute: typeof TruyenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truyen/$slug/': {
      id: '/truyen/$slug/'
      path: '/truyen/$slug'
      fullPath: '/truyen/$slug/'
      preLoaderRoute: typeof TruyenSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truyen/$slug/chuong-{$number}': {
      id: '/truyen/$slug/chuong-{$number}'
      path: '/truyen/$slug/chuong-{$number}'
      fullPath: '/truyen/$slug/chuong-{$number}'
      preLoaderRoute: typeof TruyenSlugChuongChar123numberChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DangKyRoute: DangKyRoute,
  DangNhapRoute: DangNhapRoute,
  TuSachRoute: TuSachRoute,
  TruyenIndexRoute: TruyenIndexRoute,
  TruyenSlugChuongChar123numberChar125Route:
    TruyenSlugChuongChar123numberChar125Route,
  TruyenSlugIndexRoute: TruyenSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
